/* GENERATED by scripts/typegen.ts from src/sanity/queries.ts. Do not edit; run `pnpm typegen`. */
import { defineQuery } from 'groq'

export const artistBySlugQuery =
  defineQuery(`*[_type == "artist" && slug.current == $slug][0]{
  _id, name, "slug": slug.current, "portrait": portrait{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, bio, links[]{label, href}, seo{ title, description, image, noIndex },
  "artworks": *[_type == "artwork" && artist._ref == ^._id] | order(year desc){ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }
}`)

export const artistsQuery = defineQuery(
  `*[_type == "artist"] | order(name asc){ _id, name, "slug": slug.current, "portrait": portrait{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } } }`,
)

export const artworkBySlugQuery =
  defineQuery(`*[_type == "artwork" && slug.current == $slug][0]{
  _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags, caption, dimensions, "images": images[]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, description,
  exhibitions[]->{ _id, title, "slug": slug.current }, seo{ title, description, image, noIndex }
}`)

export const artworkFiltersQuery = defineQuery(`{
  "artists": *[_type == "artist" && count(*[_type == "artwork" && references(^._id)]) > 0] | order(name asc){ _id, name, "slug": slug.current },
  "years": array::unique(*[_type == "artwork" && defined(year)].year) | order(@ desc),
  "media": array::unique(*[_type == "artwork" && defined(medium)].medium) | order(@ asc),
  "collections": array::unique(*[_type == "artwork" && defined(collection)].collection) | order(@ asc),
  "tags": array::unique(*[_type == "artwork" && defined(tags)].tags[]) | order(@ asc)
}`)

export const artworksQuery = defineQuery(`*[_type == "artwork"
  && ($artist == "" || artist->slug.current == $artist)
  && ($year == 0 || year == $year)
  && ($medium == "" || medium == $medium)
  && ($collection == "" || collection == $collection)
  && ($tagFilter == "" || $tagFilter in tags)
  && ($featured == false || featured == true)
] | order(featured desc, coalesce(date, string(year) + "-01-01") desc, title asc)[0...$limit]{ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }`)

export const eventBySlugQuery = defineQuery(
  `*[_type == "event" && slug.current == $slug][0]{ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current }, ticketUrl, body, seo{ title, description, image, noIndex } }`,
)

export const eventSeriesQuery = defineQuery(
  `*[_type == "eventSeries"] | order(title asc){ _id, title, "slug": slug.current }`,
)

export const eventsQuery =
  defineQuery(`*[_type == "event" && start >= $from && start < $to
  && ($series == "" || series->slug.current == $series)
] | order(start asc){ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current } }`)

export const exhibitionBySlugQuery =
  defineQuery(`*[_type == "exhibition" && slug.current == $slug][0]{
  _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current }, body, "images": images[]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, pressLinks[]{label, href},
  "pressRelease": select(defined(pressRelease.asset) => { "url": pressRelease.asset->url, "label": pressReleaseLabel }), seo{ title, description, image, noIndex },
  "artworks": artworks[]->{ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }
}`)

export const exhibitionsQuery = defineQuery(`{
  "current": *[_type == "exhibition" && start <= $today && (!defined(end) || end >= $today)] | order(start desc){ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } },
  "upcoming": *[_type == "exhibition" && start > $today] | order(start asc){ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } },
  "past": *[_type == "exhibition" && defined(end) && end < $today] | order(start desc)[0...$limit]{ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } }
}`)

export const pageBySlugQuery =
  defineQuery(`*[_type == "page" && slug.current == $slug][0]{
  _id, title, "slug": slug.current, blocks[]{ _key, _type, _type == "artistList" => { eyebrow, heading, columns },
  _type == "artworkGrid" => { eyebrow, heading, intro, columns, collection, limit, featuredOnly, showFilters, cta },
  _type == "cardGrid" => { eyebrow, heading, columns, cards[]{ _key, title, body, image, link } },
  _type == "contactForm" => { eyebrow, heading, intro, showSubject, buttonLabel, successMessage, aside },
  _type == "eventCalendar" => { eyebrow, heading, view, limit, showFilters, cta },
  _type == "exhibitionList" => { eyebrow, heading, mode, pastLimit, cta },
  _type == "hero" => { layout, eyebrow, heading, body, cta, image },
  _type == "newsletterSignup" => { eyebrow, heading, body, buttonLabel, tone },
  _type == "postList" => { eyebrow, heading, limit, columns, cta },
  _type == "richTextBlock" => { heading, content } }, seo{ title, description, image, noIndex }
}`)

export const postBySlugQuery = defineQuery(
  `*[_type == "post" && slug.current == $slug][0]{ _id, title, "slug": slug.current, date, excerpt, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, tags, body, seo{ title, description, image, noIndex } }`,
)

export const postsQuery = defineQuery(
  `*[_type == "post" && ($tagFilter == "" || $tagFilter in tags)] | order(date desc)[0...$limit]{ _id, title, "slug": slug.current, date, excerpt, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, tags }`,
)

export const siteSettingsQuery = defineQuery(`*[_type == "siteSettings"][0]{
  siteName, logo, nav[]{label, href}, footerText, social[]{label, href}, analyticsId,
  seo{ title, description, image, noIndex }, contactEmail, newsletter{provider, actionUrl}
}`)

export const sitemapQuery = defineQuery(`{
  "pages": *[_type == "page" && seo.noIndex != true]{ "slug": slug.current, _updatedAt },
  "artworks": *[_type == "artwork"]{ "slug": slug.current, _updatedAt },
  "artists": *[_type == "artist"]{ "slug": slug.current, _updatedAt },
  "exhibitions": *[_type == "exhibition"]{ "slug": slug.current, _updatedAt },
  "events": *[_type == "event"]{ "slug": slug.current, _updatedAt },
  "posts": *[_type == "post"]{ "slug": slug.current, _updatedAt }
}`)

export const upcomingEventsQuery =
  defineQuery(`*[_type == "event" && (start >= $now || (defined(end) && end >= $now))
  && ($series == "" || series->slug.current == $series)
] | order(start asc)[0...$limit]{ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current } }`)
