/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../node_modules/.cache/typegen/schema.json
export type RichTextBlock = {
  _type: 'richTextBlock'
  heading?: string
  content?: RichText
}

export type PostList = {
  _type: 'postList'
  eyebrow?: string
  heading?: string
  limit?: number
  columns?: 2 | 3
  cta?: Link
}

export type NewsletterSignup = {
  _type: 'newsletterSignup'
  eyebrow?: string
  heading?: string
  body?: string
  buttonLabel?: string
  tone?: 'default' | 'alt' | 'ink'
}

export type Hero = {
  _type: 'hero'
  layout?: 'split' | 'panel'
  eyebrow?: string
  heading?: string
  body?: string
  cta?: Link
  image?: ImageWithAlt
}

export type ExhibitionList = {
  _type: 'exhibitionList'
  eyebrow?: string
  heading?: string
  mode?: 'current' | 'currentUpcoming' | 'all' | 'past'
  pastLimit?: number
  cta?: Link
}

export type EventCalendar = {
  _type: 'eventCalendar'
  eyebrow?: string
  heading?: string
  view?: 'list' | 'month' | 'both'
  limit?: number
  showFilters?: boolean
  cta?: Link
}

export type ContactForm = {
  _type: 'contactForm'
  eyebrow?: string
  heading?: string
  intro?: string
  showSubject?: boolean
  buttonLabel?: string
  successMessage?: string
  aside?: RichText
}

export type CardGrid = {
  _type: 'cardGrid'
  eyebrow?: string
  heading?: string
  columns?: 2 | 3 | 4
  cards?: Array<{
    title?: string
    body?: string
    image?: ImageWithAlt
    link?: Link
    _type: 'card'
    _key: string
  }>
}

export type ArtworkGrid = {
  _type: 'artworkGrid'
  eyebrow?: string
  heading?: string
  intro?: string
  columns?: 2 | 3 | 4
  collection?: string
  limit?: number
  featuredOnly?: boolean
  showFilters?: boolean
  cta?: Link
}

export type ArtistList = {
  _type: 'artistList'
  eyebrow?: string
  heading?: string
  columns?: 2 | 3 | 4
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteName?: string
  logo?: ImageWithAlt
  nav?: Array<
    {
      _key: string
    } & Link
  >
  footerText?: string
  social?: Array<
    {
      _key: string
    } & Link
  >
  analyticsId?: string
  seo?: Seo
  contactEmail?: string
  newsletter?: {
    provider?: 'mailchimp' | 'buttondown' | 'convertkit' | 'klaviyo' | 'generic'
    actionUrl?: string
  }
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  image?: ImageWithAlt
  noIndex?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ImageWithAlt = {
  _type: 'imageWithAlt'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  caption?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Submission = {
  _id: string
  _type: 'submission'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  email?: string
  subject?: string
  message?: string
  page?: string
  receivedAt?: string
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  date?: string
  excerpt?: string
  image?: ImageWithAlt
  body?: RichText
  tags?: Array<string>
  seo?: Seo
}

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type VenueReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'venue'
}

export type EventSeriesReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'eventSeries'
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  start?: string
  end?: string
  allDay?: boolean
  venue?: VenueReference
  location?: string
  price?: string
  ticketUrl?: string
  series?: EventSeriesReference
  image?: ImageWithAlt
  body?: RichText
  seo?: Seo
}

export type Venue = {
  _id: string
  _type: 'venue'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  address?: string
  mapLink?: string
}

export type EventSeries = {
  _id: string
  _type: 'eventSeries'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type ArtistReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'artist'
}

export type ArtworkReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'artwork'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type Exhibition = {
  _id: string
  _type: 'exhibition'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  start?: string
  end?: string
  venue?: string
  artists?: Array<
    {
      _key: string
    } & ArtistReference
  >
  artworks?: Array<
    {
      _key: string
    } & ArtworkReference
  >
  image?: ImageWithAlt
  body?: RichText
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  pressLinks?: Array<
    {
      _key: string
    } & Link
  >
  pressRelease?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  pressReleaseLabel?: string
  seo?: Seo
}

export type ExhibitionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'exhibition'
}

export type Artwork = {
  _id: string
  _type: 'artwork'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  artist?: ArtistReference
  collection?:
    | 'Paintings'
    | 'Works on Paper'
    | 'Sculpture'
    | 'Photography'
    | 'Video'
    | 'Other'
  year?: number
  date?: string
  medium?: string
  dimensions?: string
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  caption?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  description?: RichText
  exhibitions?: Array<
    {
      _key: string
    } & ExhibitionReference
  >
  tags?: Array<string>
  featured?: boolean
  seo?: Seo
}

export type Artist = {
  _id: string
  _type: 'artist'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  portrait?: ImageWithAlt
  bio?: RichText
  links?: Array<
    {
      _key: string
    } & Link
  >
  seo?: Seo
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  blocks?: Array<
    | ({
        _key: string
      } & ArtistList)
    | ({
        _key: string
      } & ArtworkGrid)
    | ({
        _key: string
      } & CardGrid)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & EventCalendar)
    | ({
        _key: string
      } & ExhibitionList)
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & NewsletterSignup)
    | ({
        _key: string
      } & PostList)
    | ({
        _key: string
      } & RichTextBlock)
  >
  seo?: Seo
}

export type Link = {
  _type: 'link'
  label?: string
  href?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | RichTextBlock
  | PostList
  | NewsletterSignup
  | Hero
  | ExhibitionList
  | EventCalendar
  | ContactForm
  | CardGrid
  | ArtworkGrid
  | ArtistList
  | SiteSettings
  | Seo
  | SanityImageAssetReference
  | ImageWithAlt
  | Submission
  | Post
  | RichText
  | Slug
  | VenueReference
  | EventSeriesReference
  | Event
  | Venue
  | EventSeries
  | ArtistReference
  | ArtworkReference
  | SanityFileAssetReference
  | Exhibition
  | ExhibitionReference
  | Artwork
  | Artist
  | Page
  | Link
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../src/sanity/queries.gen.ts
// Variable: artistBySlugQuery
// Query: *[_type == "artist" && slug.current == $slug][0]{  _id, name, "slug": slug.current, "portrait": portrait{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, bio, links[]{label, href}, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex },  "artworks": *[_type == "artwork" && artist._ref == ^._id] | order(year desc){ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }}
export type ArtistBySlugQueryResult = {
  _id: string
  name: string | null
  slug: string | null
  portrait: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  bio: RichText | null
  links: Array<{
    label: string | null
    href: string | null
  }> | null
  seo: {
    title: string | null
    description: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    noIndex: boolean | null
  } | null
  artworks: Array<{
    _id: string
    title: string | null
    slug: string | null
    year: number | null
    date: string | null
    collection:
      | 'Other'
      | 'Paintings'
      | 'Photography'
      | 'Sculpture'
      | 'Video'
      | 'Works on Paper'
      | null
    medium: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    artist: {
      _id: string
      name: string | null
      slug: string | null
    } | null
    tags: Array<string> | null
  }>
} | null

// Source: ../src/sanity/queries.gen.ts
// Variable: artistsQuery
// Query: *[_type == "artist"] | order(name asc){ _id, name, "slug": slug.current, "portrait": portrait{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } } }
export type ArtistsQueryResult = Array<{
  _id: string
  name: string | null
  slug: string | null
  portrait: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
}>

// Source: ../src/sanity/queries.gen.ts
// Variable: artworkBySlugQuery
// Query: *[_type == "artwork" && slug.current == $slug][0]{  _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags, caption, dimensions, "images": images[]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, description,  exhibitions[]->{ _id, title, "slug": slug.current }, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex }}
export type ArtworkBySlugQueryResult = {
  _id: string
  title: string | null
  slug: string | null
  year: number | null
  date: string | null
  collection:
    | 'Other'
    | 'Paintings'
    | 'Photography'
    | 'Sculpture'
    | 'Video'
    | 'Works on Paper'
    | null
  medium: string | null
  image: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  artist: {
    _id: string
    name: string | null
    slug: string | null
  } | null
  tags: Array<string> | null
  caption: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  dimensions: string | null
  images: Array<{
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  }> | null
  description: RichText | null
  exhibitions: Array<{
    _id: string
    title: string | null
    slug: string | null
  }> | null
  seo: {
    title: string | null
    description: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: ../src/sanity/queries.gen.ts
// Variable: artworkFiltersQuery
// Query: {  "artists": *[_type == "artist" && count(*[_type == "artwork" && references(^._id)]) > 0] | order(name asc){ _id, name, "slug": slug.current },  "years": array::unique(*[_type == "artwork" && defined(year)].year) | order(@ desc),  "media": array::unique(*[_type == "artwork" && defined(medium)].medium) | order(@ asc),  "collections": array::unique(*[_type == "artwork" && defined(collection)].collection) | order(@ asc),  "tags": array::unique(*[_type == "artwork" && defined(tags)].tags[]) | order(@ asc)}
export type ArtworkFiltersQueryResult = {
  artists: Array<{
    _id: string
    name: string | null
    slug: string | null
  }>
  years: Array<number>
  media: Array<string>
  collections: Array<
    | 'Other'
    | 'Paintings'
    | 'Photography'
    | 'Sculpture'
    | 'Video'
    | 'Works on Paper'
  >
  tags: Array<string>
}

// Source: ../src/sanity/queries.gen.ts
// Variable: artworksQuery
// Query: *[_type == "artwork"  && ($artist == "" || artist->slug.current == $artist)  && ($year == 0 || year == $year)  && ($medium == "" || medium == $medium)  && ($collection == "" || collection == $collection)  && ($tagFilter == "" || $tagFilter in tags)  && ($featured == false || featured == true)] | order(featured desc, coalesce(date, string(year) + "-01-01") desc, title asc)[0...$limit]{ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }
export type ArtworksQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  year: number | null
  date: string | null
  collection:
    | 'Other'
    | 'Paintings'
    | 'Photography'
    | 'Sculpture'
    | 'Video'
    | 'Works on Paper'
    | null
  medium: string | null
  image: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  artist: {
    _id: string
    name: string | null
    slug: string | null
  } | null
  tags: Array<string> | null
}>

// Source: ../src/sanity/queries.gen.ts
// Variable: eventBySlugQuery
// Query: *[_type == "event" && slug.current == $slug][0]{ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current }, ticketUrl, body, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex } }
export type EventBySlugQueryResult = {
  _id: string
  title: string | null
  slug: string | null
  start: string | null
  end: string | null
  allDay: boolean | null
  location: string | null
  venue: {
    _id: string
    name: string | null
    slug: string | null
    address: string | null
    mapLink: string | null
  } | null
  price: string | null
  image: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  series: {
    _id: string
    title: string | null
    slug: string | null
  } | null
  ticketUrl: string | null
  body: RichText | null
  seo: {
    title: string | null
    description: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: ../src/sanity/queries.gen.ts
// Variable: eventSeriesQuery
// Query: *[_type == "eventSeries"] | order(title asc){ _id, title, "slug": slug.current }
export type EventSeriesQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
}>

// Source: ../src/sanity/queries.gen.ts
// Variable: eventsQuery
// Query: *[_type == "event" && start >= $from && start < $to  && ($series == "" || series->slug.current == $series)] | order(start asc){ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current } }
export type EventsQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  start: string | null
  end: string | null
  allDay: boolean | null
  location: string | null
  venue: {
    _id: string
    name: string | null
    slug: string | null
    address: string | null
    mapLink: string | null
  } | null
  price: string | null
  image: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  series: {
    _id: string
    title: string | null
    slug: string | null
  } | null
}>

// Source: ../src/sanity/queries.gen.ts
// Variable: exhibitionBySlugQuery
// Query: *[_type == "exhibition" && slug.current == $slug][0]{  _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current }, body, "images": images[]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, pressLinks[]{label, href},  "pressRelease": select(defined(pressRelease.asset) => { "url": pressRelease.asset->url, "label": pressReleaseLabel }), seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex },  "artworks": artworks[]->{ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }}
export type ExhibitionBySlugQueryResult = {
  _id: string
  title: string | null
  slug: string | null
  start: string | null
  end: string | null
  venue: string | null
  image: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  artists: Array<{
    _id: string
    name: string | null
    slug: string | null
  }> | null
  body: RichText | null
  images: Array<{
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  }> | null
  pressLinks: Array<{
    label: string | null
    href: string | null
  }> | null
  pressRelease: {
    url: string | null
    label: string | null
  }
  seo: {
    title: string | null
    description: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    noIndex: boolean | null
  } | null
  artworks: Array<{
    _id: string
    title: string | null
    slug: string | null
    year: number | null
    date: string | null
    collection:
      | 'Other'
      | 'Paintings'
      | 'Photography'
      | 'Sculpture'
      | 'Video'
      | 'Works on Paper'
      | null
    medium: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    artist: {
      _id: string
      name: string | null
      slug: string | null
    } | null
    tags: Array<string> | null
  }> | null
} | null

// Source: ../src/sanity/queries.gen.ts
// Variable: exhibitionsQuery
// Query: {  "current": *[_type == "exhibition" && start <= $today && (!defined(end) || end >= $today)] | order(start desc){ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } },  "upcoming": *[_type == "exhibition" && start > $today] | order(start asc){ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } },  "past": *[_type == "exhibition" && defined(end) && end < $today] | order(start desc)[0...$limit]{ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } }}
export type ExhibitionsQueryResult = {
  current: Array<{
    _id: string
    title: string | null
    slug: string | null
    start: string | null
    end: string | null
    venue: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    artists: Array<{
      _id: string
      name: string | null
      slug: string | null
    }> | null
  }>
  upcoming: Array<{
    _id: string
    title: string | null
    slug: string | null
    start: string | null
    end: string | null
    venue: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    artists: Array<{
      _id: string
      name: string | null
      slug: string | null
    }> | null
  }>
  past: Array<{
    _id: string
    title: string | null
    slug: string | null
    start: string | null
    end: string | null
    venue: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    artists: Array<{
      _id: string
      name: string | null
      slug: string | null
    }> | null
  }>
}

// Source: ../src/sanity/queries.gen.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  _id, title, "slug": slug.current, blocks[]{ _key, _type, _type == "artistList" => { eyebrow, heading, columns },  _type == "artworkGrid" => { eyebrow, heading, intro, columns, collection, limit, featuredOnly, showFilters, cta },  _type == "cardGrid" => { eyebrow, heading, columns, cards[]{ _key, title, body, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, link } },  _type == "contactForm" => { eyebrow, heading, intro, showSubject, buttonLabel, successMessage, aside },  _type == "eventCalendar" => { eyebrow, heading, view, limit, showFilters, cta },  _type == "exhibitionList" => { eyebrow, heading, mode, pastLimit, cta },  _type == "hero" => { layout, eyebrow, heading, body, cta, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } } },  _type == "newsletterSignup" => { eyebrow, heading, body, buttonLabel, tone },  _type == "postList" => { eyebrow, heading, limit, columns, cta },  _type == "richTextBlock" => { heading, content } }, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex }}
export type PageBySlugQueryResult = {
  _id: string
  title: string | null
  slug: string | null
  blocks: Array<
    | {
        _key: string
        _type: 'artistList'
        eyebrow: string | null
        heading: string | null
        columns: 2 | 3 | 4 | null
      }
    | {
        _key: string
        _type: 'artworkGrid'
        eyebrow: string | null
        heading: string | null
        intro: string | null
        columns: 2 | 3 | 4 | null
        collection: string | null
        limit: number | null
        featuredOnly: boolean | null
        showFilters: boolean | null
        cta: Link | null
      }
    | {
        _key: string
        _type: 'cardGrid'
        eyebrow: string | null
        heading: string | null
        columns: 2 | 3 | 4 | null
        cards: Array<{
          _key: string
          title: string | null
          body: string | null
          image: {
            _type: 'imageWithAlt'
            asset: SanityImageAssetReference | null
            alt: string | null
            caption: Array<{
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal'
              listItem?: never
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }> | null
            hotspot: SanityImageHotspot | null
            crop: SanityImageCrop | null
            meta: {
              lqip: string | null
              width: number | null
              height: number | null
            } | null
          } | null
          link: Link | null
        }> | null
      }
    | {
        _key: string
        _type: 'contactForm'
        eyebrow: string | null
        heading: string | null
        intro: string | null
        showSubject: boolean | null
        buttonLabel: string | null
        successMessage: string | null
        aside: RichText | null
      }
    | {
        _key: string
        _type: 'eventCalendar'
        eyebrow: string | null
        heading: string | null
        view: 'both' | 'list' | 'month' | null
        limit: number | null
        showFilters: boolean | null
        cta: Link | null
      }
    | {
        _key: string
        _type: 'exhibitionList'
        eyebrow: string | null
        heading: string | null
        mode: 'all' | 'current' | 'currentUpcoming' | 'past' | null
        pastLimit: number | null
        cta: Link | null
      }
    | {
        _key: string
        _type: 'hero'
        layout: 'panel' | 'split' | null
        eyebrow: string | null
        heading: string | null
        body: string | null
        cta: Link | null
        image: {
          _type: 'imageWithAlt'
          asset: SanityImageAssetReference | null
          alt: string | null
          caption: Array<{
            children?: Array<{
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }>
            style?: 'normal'
            listItem?: never
            markDefs?: Array<{
              href?: string
              _type: 'link'
              _key: string
            }>
            level?: number
            _type: 'block'
            _key: string
          }> | null
          hotspot: SanityImageHotspot | null
          crop: SanityImageCrop | null
          meta: {
            lqip: string | null
            width: number | null
            height: number | null
          } | null
        } | null
      }
    | {
        _key: string
        _type: 'newsletterSignup'
        eyebrow: string | null
        heading: string | null
        body: string | null
        buttonLabel: string | null
        tone: 'alt' | 'default' | 'ink' | null
      }
    | {
        _key: string
        _type: 'postList'
        eyebrow: string | null
        heading: string | null
        limit: number | null
        columns: 2 | 3 | null
        cta: Link | null
      }
    | {
        _key: string
        _type: 'richTextBlock'
        heading: string | null
        content: RichText | null
      }
  > | null
  seo: {
    title: string | null
    description: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: ../src/sanity/queries.gen.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0]{ _id, title, "slug": slug.current, date, excerpt, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, tags, body, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex } }
export type PostBySlugQueryResult = {
  _id: string
  title: string | null
  slug: string | null
  date: string | null
  excerpt: string | null
  image: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  tags: Array<string> | null
  body: RichText | null
  seo: {
    title: string | null
    description: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: ../src/sanity/queries.gen.ts
// Variable: postsQuery
// Query: *[_type == "post" && ($tagFilter == "" || $tagFilter in tags)] | order(date desc)[0...$limit]{ _id, title, "slug": slug.current, date, excerpt, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, tags }
export type PostsQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  date: string | null
  excerpt: string | null
  image: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  tags: Array<string> | null
}>

// Source: ../src/sanity/queries.gen.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  siteName, "logo": logo{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, nav[]{label, href}, footerText, social[]{label, href}, analyticsId,  seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex }, contactEmail, newsletter{provider, actionUrl}}
export type SiteSettingsQueryResult = {
  siteName: string | null
  logo: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  nav: Array<{
    label: string | null
    href: string | null
  }> | null
  footerText: string | null
  social: Array<{
    label: string | null
    href: string | null
  }> | null
  analyticsId: string | null
  seo: {
    title: string | null
    description: string | null
    image: {
      _type: 'imageWithAlt'
      asset: SanityImageAssetReference | null
      alt: string | null
      caption: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal'
        listItem?: never
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }> | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
      meta: {
        lqip: string | null
        width: number | null
        height: number | null
      } | null
    } | null
    noIndex: boolean | null
  } | null
  contactEmail: string | null
  newsletter: {
    provider:
      | 'buttondown'
      | 'convertkit'
      | 'generic'
      | 'klaviyo'
      | 'mailchimp'
      | null
    actionUrl: string | null
  } | null
} | null

// Source: ../src/sanity/queries.gen.ts
// Variable: sitemapQuery
// Query: {  "pages": *[_type == "page" && seo.noIndex != true]{ "slug": slug.current, _updatedAt },  "artworks": *[_type == "artwork"]{ "slug": slug.current, _updatedAt },  "artists": *[_type == "artist"]{ "slug": slug.current, _updatedAt },  "exhibitions": *[_type == "exhibition"]{ "slug": slug.current, _updatedAt },  "events": *[_type == "event"]{ "slug": slug.current, _updatedAt },  "posts": *[_type == "post"]{ "slug": slug.current, _updatedAt }}
export type SitemapQueryResult = {
  pages: Array<{
    slug: string | null
    _updatedAt: string
  }>
  artworks: Array<{
    slug: string | null
    _updatedAt: string
  }>
  artists: Array<{
    slug: string | null
    _updatedAt: string
  }>
  exhibitions: Array<{
    slug: string | null
    _updatedAt: string
  }>
  events: Array<{
    slug: string | null
    _updatedAt: string
  }>
  posts: Array<{
    slug: string | null
    _updatedAt: string
  }>
}

// Source: ../src/sanity/queries.gen.ts
// Variable: upcomingEventsQuery
// Query: *[_type == "event" && (start >= $now || (defined(end) && end >= $now))  && ($series == "" || series->slug.current == $series)] | order(start asc)[0...$limit]{ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current } }
export type UpcomingEventsQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  start: string | null
  end: string | null
  allDay: boolean | null
  location: string | null
  venue: {
    _id: string
    name: string | null
    slug: string | null
    address: string | null
    mapLink: string | null
  } | null
  price: string | null
  image: {
    _type: 'imageWithAlt'
    asset: SanityImageAssetReference | null
    alt: string | null
    caption: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    meta: {
      lqip: string | null
      width: number | null
      height: number | null
    } | null
  } | null
  series: {
    _id: string
    title: string | null
    slug: string | null
  } | null
}>

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "artist" && slug.current == $slug][0]{\n  _id, name, "slug": slug.current, "portrait": portrait{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, bio, links[]{label, href}, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex },\n  "artworks": *[_type == "artwork" && artist._ref == ^._id] | order(year desc){ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }\n}': ArtistBySlugQueryResult
    '*[_type == "artist"] | order(name asc){ _id, name, "slug": slug.current, "portrait": portrait{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } } }': ArtistsQueryResult
    '*[_type == "artwork" && slug.current == $slug][0]{\n  _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags, caption, dimensions, "images": images[]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, description,\n  exhibitions[]->{ _id, title, "slug": slug.current }, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex }\n}': ArtworkBySlugQueryResult
    '{\n  "artists": *[_type == "artist" && count(*[_type == "artwork" && references(^._id)]) > 0] | order(name asc){ _id, name, "slug": slug.current },\n  "years": array::unique(*[_type == "artwork" && defined(year)].year) | order(@ desc),\n  "media": array::unique(*[_type == "artwork" && defined(medium)].medium) | order(@ asc),\n  "collections": array::unique(*[_type == "artwork" && defined(collection)].collection) | order(@ asc),\n  "tags": array::unique(*[_type == "artwork" && defined(tags)].tags[]) | order(@ asc)\n}': ArtworkFiltersQueryResult
    '*[_type == "artwork"\n  && ($artist == "" || artist->slug.current == $artist)\n  && ($year == 0 || year == $year)\n  && ($medium == "" || medium == $medium)\n  && ($collection == "" || collection == $collection)\n  && ($tagFilter == "" || $tagFilter in tags)\n  && ($featured == false || featured == true)\n] | order(featured desc, coalesce(date, string(year) + "-01-01") desc, title asc)[0...$limit]{ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }': ArtworksQueryResult
    '*[_type == "event" && slug.current == $slug][0]{ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current }, ticketUrl, body, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex } }': EventBySlugQueryResult
    '*[_type == "eventSeries"] | order(title asc){ _id, title, "slug": slug.current }': EventSeriesQueryResult
    '*[_type == "event" && start >= $from && start < $to\n  && ($series == "" || series->slug.current == $series)\n] | order(start asc){ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current } }': EventsQueryResult
    '*[_type == "exhibition" && slug.current == $slug][0]{\n  _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current }, body, "images": images[]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, pressLinks[]{label, href},\n  "pressRelease": select(defined(pressRelease.asset) => { "url": pressRelease.asset->url, "label": pressReleaseLabel }), seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex },\n  "artworks": artworks[]->{ _id, title, "slug": slug.current, year, date, collection, medium, "image": images[0]{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artist->{ _id, name, "slug": slug.current }, tags }\n}': ExhibitionBySlugQueryResult
    '{\n  "current": *[_type == "exhibition" && start <= $today && (!defined(end) || end >= $today)] | order(start desc){ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } },\n  "upcoming": *[_type == "exhibition" && start > $today] | order(start asc){ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } },\n  "past": *[_type == "exhibition" && defined(end) && end < $today] | order(start desc)[0...$limit]{ _id, title, "slug": slug.current, start, end, venue, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, artists[]->{ _id, name, "slug": slug.current } }\n}': ExhibitionsQueryResult
    '*[_type == "page" && slug.current == $slug][0]{\n  _id, title, "slug": slug.current, blocks[]{ _key, _type, _type == "artistList" => { eyebrow, heading, columns },\n  _type == "artworkGrid" => { eyebrow, heading, intro, columns, collection, limit, featuredOnly, showFilters, cta },\n  _type == "cardGrid" => { eyebrow, heading, columns, cards[]{ _key, title, body, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, link } },\n  _type == "contactForm" => { eyebrow, heading, intro, showSubject, buttonLabel, successMessage, aside },\n  _type == "eventCalendar" => { eyebrow, heading, view, limit, showFilters, cta },\n  _type == "exhibitionList" => { eyebrow, heading, mode, pastLimit, cta },\n  _type == "hero" => { layout, eyebrow, heading, body, cta, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } } },\n  _type == "newsletterSignup" => { eyebrow, heading, body, buttonLabel, tone },\n  _type == "postList" => { eyebrow, heading, limit, columns, cta },\n  _type == "richTextBlock" => { heading, content } }, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex }\n}': PageBySlugQueryResult
    '*[_type == "post" && slug.current == $slug][0]{ _id, title, "slug": slug.current, date, excerpt, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, tags, body, seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex } }': PostBySlugQueryResult
    '*[_type == "post" && ($tagFilter == "" || $tagFilter in tags)] | order(date desc)[0...$limit]{ _id, title, "slug": slug.current, date, excerpt, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, tags }': PostsQueryResult
    '*[_type == "siteSettings"][0]{\n  siteName, "logo": logo{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, nav[]{label, href}, footerText, social[]{label, href}, analyticsId,\n  seo{ title, description, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, noIndex }, contactEmail, newsletter{provider, actionUrl}\n}': SiteSettingsQueryResult
    '{\n  "pages": *[_type == "page" && seo.noIndex != true]{ "slug": slug.current, _updatedAt },\n  "artworks": *[_type == "artwork"]{ "slug": slug.current, _updatedAt },\n  "artists": *[_type == "artist"]{ "slug": slug.current, _updatedAt },\n  "exhibitions": *[_type == "exhibition"]{ "slug": slug.current, _updatedAt },\n  "events": *[_type == "event"]{ "slug": slug.current, _updatedAt },\n  "posts": *[_type == "post"]{ "slug": slug.current, _updatedAt }\n}': SitemapQueryResult
    '*[_type == "event" && (start >= $now || (defined(end) && end >= $now))\n  && ($series == "" || series->slug.current == $series)\n] | order(start asc)[0...$limit]{ _id, title, "slug": slug.current, start, end, allDay, location, venue->{ _id, name, "slug": slug.current, address, mapLink }, price, "image": image{ _type, asset, alt, caption, hotspot, crop, "meta": asset->metadata{ lqip, "width": dimensions.width, "height": dimensions.height } }, series->{ _id, title, "slug": slug.current } }': UpcomingEventsQueryResult
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
