/* Regenerate the block inventory in AGENTS.md from src/blocks/schemas.ts and the primitives in
   src/ui/index.tsx, so the build agent reads the real list instead of guessing.
   Run: pnpm inventory   (the local runner does this before and after every agent run) */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { execFileSync } from 'node:child_process'
import { build } from 'vite'

type Field = {
  name: string
  type: string
  title?: string
  description?: string
  validation?: unknown
  options?: { list?: Array<string | number | { value: string | number }> }
  of?: Array<{ type: string; fields?: Array<Field> }>
  fields?: Array<Field>
}
type Schema = {
  name: string
  title?: string
  description?: string
  fields?: Array<Field>
}

const START = '<!-- inventory:start -->'
const END = '<!-- inventory:end -->'

// Bundle schemas.ts for Node (extensionless TS imports need a bundler), import it, throw the bundle away.
// Inside node_modules so the bundle can still resolve @sanity/types.
const out = join(process.cwd(), 'node_modules/.cache/inventory')
await mkdir(out, { recursive: true })
await build({
  configFile: false,
  logLevel: 'silent',
  build: {
    ssr: 'src/blocks/schemas.ts',
    outDir: out,
    emptyOutDir: true,
    rollupOptions: { external: [/^@sanity\//] },
  },
})
const { blockSchemaEntries } = (await import(
  pathToFileURL(join(out, 'schemas.js')).href
)) as {
  blockSchemaEntries: Array<{ schema: Schema }>
}
await rm(out, { recursive: true, force: true })

function fieldSig(f: Field): string {
  const req = f.validation ? '*' : ''
  const list = f.options?.list
    ?.map((o) => (typeof o === 'object' ? o.value : o))
    .join('/')
  if (f.type === 'array') {
    const of = f.of ?? []
    const inner = of
      .map((o) =>
        o.fields ? `{${o.fields.map(fieldSig).join(', ')}}` : o.type,
      )
      .join('|')
    return `${f.name}${req}: ${inner}[]`
  }
  if (f.type === 'object' && f.fields)
    return `${f.name}${req}: {${f.fields.map(fieldSig).join(', ')}}`
  return `${f.name}${req}${list ? ` (${list})` : f.type === 'string' || f.type === 'text' ? '' : `: ${f.type}`}`
}

const rows = blockSchemaEntries.map(({ schema }) => {
  const folder = schema.name
    .replace(/^./, (c) => c.toUpperCase())
    .replace(/Block$/, '')
  const use = (schema.description ?? '')
    .replace(/\|/g, '\\|')
    .replace(/\s+/g, ' ')
  const fields = (schema.fields ?? [])
    .map(fieldSig)
    .join(', ')
    .replace(/\|/g, '\\|')
  return `| \`${schema.name}\` | \`src/blocks/${folder}/\` | ${use} | ${fields} |`
})

const ui = await readFile('src/ui/index.tsx', 'utf8')
const primitives = [...ui.matchAll(/^export function (\w+)/gm)].map((m) => m[1])

const table = [
  START,
  `_Generated by \`pnpm inventory\` from \`src/blocks/schemas.ts\`; do not edit by hand. ${rows.length} blocks._`,
  '',
  '| Block | Folder | Use for | Fields (`*` required) |',
  '| --- | --- | --- | --- |',
  ...rows,
  '',
  `Primitives in \`src/ui/index.tsx\`: ${primitives.map((p) => `\`${p}\``).join(', ')}.`,
  END,
].join('\n')

const path = 'AGENTS.md'
const md = await readFile(path, 'utf8')
const next = md.includes(START)
  ? md.replace(new RegExp(`${START}[\\s\\S]*?${END}`), table)
  : `${md.trimEnd()}\n\n## Block inventory\n\n${table}\n`
if (next !== md) {
  await writeFile(path, next)
  execFileSync('pnpm', ['exec', 'prettier', '--write', path], {
    stdio: 'ignore',
  })
  console.log(
    `AGENTS.md: inventory updated (${rows.length} blocks, ${primitives.length} primitives)`,
  )
} else console.log('AGENTS.md: inventory unchanged')
