/* Sanity typegen for queries that are composed at runtime. The block system builds its projection
   from the registry, so the GROQ in src/sanity/queries.ts is not statically analysable. This
   evaluates it, writes every query as a literal `defineQuery(...)` to src/sanity/queries.gen.ts,
   then runs `sanity schema extract` + `sanity typegen generate` over that file. The app imports
   queries from queries.gen.ts, so `client.fetch(query)` is typed end to end with no hand-written
   result types. Run after changing a schema, a block projection or a query: `pnpm typegen`. */
import { execFileSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { build } from 'vite'

/* Only public Sanity ids are needed (the studio config reads them for `schema extract`). Locally
   they come from .env; in CI there is no .env, so fall back to the committed .env.production. */
process.loadEnvFile(existsSync('.env') ? '.env' : '.env.production')
const env = {
  ...process.env,
  SANITY_STUDIO_PROJECT_ID:
    process.env.SANITY_STUDIO_PROJECT_ID ?? process.env.VITE_SANITY_PROJECT_ID,
  SANITY_STUDIO_DATASET:
    process.env.SANITY_STUDIO_DATASET ?? process.env.VITE_SANITY_DATASET,
}

const outDir = 'node_modules/.cache/typegen'
await build({
  configFile: false,
  logLevel: 'error',
  resolve: { tsconfigPaths: true },
  build: {
    ssr: 'src/sanity/queries.ts',
    outDir,
    emptyOutDir: true,
    rollupOptions: { output: { entryFileNames: 'queries.mjs' } },
  },
})
const mod: Record<string, string | ((...a: Array<string>) => string)> =
  await import(`${process.cwd()}/${outDir}/queries.mjs?${Date.now()}`)
const queries = Object.entries(mod).filter(
  (e): e is [string, string] =>
    typeof e[1] === 'string' && e[0].endsWith('Query'),
)
const literal = (s: string) =>
  s.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('${', '\\${')
await writeFile(
  'src/sanity/queries.gen.ts',
  `/* GENERATED by scripts/typegen.ts from src/sanity/queries.ts. Do not edit; run \`pnpm typegen\`. */
import { defineQuery } from 'groq'

${queries.map(([name, q]) => `export const ${name} = defineQuery(\`${literal(q)}\`)`).join('\n\n')}
`,
)
console.log(`queries.gen.ts: ${queries.length} queries`)
const run = (args: Array<string>) =>
  execFileSync('pnpm', ['--filter', 'studio', 'exec', 'sanity', ...args], {
    stdio: 'inherit',
    env,
  })
run([
  'schema',
  'extract',
  '--path',
  '../node_modules/.cache/typegen/schema.json',
])
run(['typegen', 'generate'])
execFileSync(
  'pnpm',
  ['exec', 'oxfmt', 'src/sanity/queries.gen.ts', 'src/sanity/sanity.types.ts'],
  {
    stdio: 'ignore',
  },
)
